language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements.txt
  - python3 setup.py install
script:
  - cd tests
  - python3 k_means.py
  - python3 linear_regression.py
  - python3 neuralnetwork.py
  - python3 cnn.py
  - python3 logistic_regression.py